# Ruff configuration file - see https://docs.astral.sh/ruff/configuration/
extend-exclude = [
    ".venv",
]

line-length = 120
indent-width = 4

# Assume Python 3.11
target-version = "py311"

output-format = "pylint"

[lint]
# Enable preview for rules that are still in development or are not yet stable (inlcludes many pylint rules).
preview = true

# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`) codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
# These are the defaults:
# select = ["E4", "E7", "E9", "F"]
# See https://docs.astral.sh/ruff/configuration/
extend-select = [
    "Q",  # flake8-quotes https://docs.astral.sh/ruff/rules/#flake8-quotes-q
    "PL",  # pylint https://docs.astral.sh/ruff/rules/#pylint-pl
    "W",  # pycodestyle warnings https://docs.astral.sh/ruff/rules/#warning-w
    "E",  # pycodestyle errors https://docs.astral.sh/ruff/rules/#error-e
    "B",  # flake8-bugbear https://docs.astral.sh/ruff/rules/#flake8-bugbear-b
]
ignore = []

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Configure flake8-quotes behaviour
[lint.flake8-quotes]
inline-quotes = "double"
multiline-quotes = "double"
docstring-quotes = "double"
avoid-escape = true


[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

# Enable auto-formatting of code examples in docstrings. Markdown,
# reStructuredText code/literal blocks and doctests are all supported.
#
# This is currently disabled by default, but it is planned for this
# to be opt-out in the future.
docstring-code-format = false

# Set the line length limit used when formatting code snippets in
# docstrings.
#
# This only has an effect when the `docstring-code-format` setting is
# enabled.
docstring-code-line-length = "dynamic"