AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: 10
    Tracing: Active
    Runtime: python3.11
    Environment:
      Variables:
        POWERTOOLS_SERVICE_NAME: "BoilerplateService"
        LOG_LEVEL: "INFO"
Resources:
  MyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: MyItems
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

  PostFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/services/api/post.handler
      Events:
        Api:
          Type: Api
          Properties:
            Path: /item
            Method: post
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MyTable
